package com.example.myapk4.model

import com.example.myapk4.R
object ProductDataResource {
    val dummyProduct = listOf(
        Product(1, R.drawable.ant_man, "Ant-Man", "Ant-Man, the microscopic hero of the Marvel Cinematic Universe (MCU), returns in his third epic adventure, \"Ant-Man and the Wasp: Quantumania.\" This time, he faces an unimaginable enemy, Kang the Conqueror, a villain who controls time. Scott Lang, again brilliantly played by Paul Rudd, must join forces with Wasp and her allies on an exciting journey to save the world from a threat greater than ever. With extraordinary action, entertaining humor and stunning visual effects, this film will take the audience on a journey that does not include the dimensions of time and space.",50000 ),
        Product(2, R.drawable.flash, "Flash","An action-packed tale about Barry Allen, a forensic scientist who gains extraordinary powers after being struck by lightning, transforming him into the superhero known as Flash. Using his super speed, Barry fights crime in Central City, facing powerful supervillains who misuse their abilities for evil. While maintaining his secret identity, Barry seeks to understand the origin of his powers and unravel the mystery surrounding his mother's murder. Along the way, he explores his personal relationships, forms friendships with other heroes, and becomes a protector of the city and the world.", 50000 ),
        Product(3, R.drawable.gatot_kaca, "Gatot Kaca"," An epic filled with action narrating the journey of the legendary hero from Javanese mythology. Gatotkaca, with his formidable strength, emerges as the guardian of the kingdom, defending it from various threats and enemies. His story is replete with epic adventures, camaraderie, and values of heroism. Gatotkaca utilizes his powers to protect his people and maintain peace in his kingdom. In battles against mystical creatures and evil villains, he proves his bravery and loyalty to justice, inspiring future generations with his legendary heroism and becoming an unforgettable cultural icon in Indonesia.", 50000 ),
        Product(4, R.drawable.guardian_galaxy, "Guardian Of Galaxy","An outer-space adventure combining action, comedy, and unique characters. The spacefaring group consisting of Peter Quill, Gamora, Drax, Rocket, and Groot strives to protect the galaxy from intergalactic villains and evil cosmic entities. With intelligence, strength, and an array of weapons, they form an unexpected bond as they face powerful adversaries. While unconventional as heroes, they prove that even the most unusual individuals can make a significant difference in safeguarding the galaxy from catastrophe. The film celebrates diversity and unity in the struggle against evil.", 50000 ),
        Product(5, R.drawable.iron_man, "Iron Man", "ony Stark, also known as Iron Man, is a genius, billionaire, playboy, and philanthropist who creates a sophisticated suit of armor that grants him superhuman strength and durability. He utilizes the suit to protect the world from threats and becomes a member of the Avengers. Iron Man possesses various powers and weapons, including flight, incredible physical strength, and energy-based weaponry. Additionally, Iron Man is recognized as a symbol of mental fortitude and resilience in facing life's challenges",50000 ),
        Product(6, R.drawable.shazam, "Shazam", "",50000 ),
        Product(7, R.drawable.sri_asih, "Sri Asih", "Sri Asih is an Indonesian female superhero created by R.A. Kosasih in 1954. In the 2022 film adaptation, Sri Asih is portrayed as a professional boxer named Alana who struggles with her excessive emotions. Sri Asih possesses incredibly powerful superhuman abilities that only emerge when used for good, not anger or vengeance. The film, starring Pevita Pearce, Reza Rahadian, Christine Hakim, Dimas Anggara, Jefri Nichol, and Surya Saputra, showcases Sri Asih's legendary heroism and makes her an unforgettable cultural icon in Indonesia.",50000 ),
        Product(8, R.drawable.superman, "Super Man", "An epic tale of the origin of Superman, also known as Kal-El from the planet Krypton. The film depicts his heroic journey, arriving on Earth as a baby and developing extraordinary powers due to exposure to yellow sunlight. However, when a significant threat emerges from Kryptonian enemies determined to destroy Earth, Superman must decide between his roots and his new home. The film's epic battles test his strength and character, conveying messages of hope, courage, and sacrifice.",50000 ),
        Product(9, R.drawable.venom, "Venom", "Venom is an anti-hero character with superhuman powers and immunity to sharp weapons. First appearing in the comic \"The Amazing Spider-Man #300\" in 1988, Venom possesses incredible physical abilities such as speed, strength, and high durability. He can regenerate and produce spider-web-like material similar to Spider-Man. However, Venom has a weakness to electricity. The 2018 film, starring Tom Hardy, explores Venom's character in various media, including film, television, and video games, and was a box office success.",50000 ),
        Product(10, R.drawable.wakanda, "Wakanda", "Wakanda stands as a mesmerizing and awe-inspiring fictional African nation, shrouded in mystery and known for its abundant reserves of the rare and powerful vibranium. Nestled within the heart of the continent, this clandestine kingdom is more than just a sovereign land; it is a beacon of technological brilliance and cultural richness At the core of Wakandas allure is its coveted vibranium, a precious metal with unparalleled properties. Renowned for its ability to absorb and store energy, vibranium has fueled the technological advancements that set Wakanda apart from the rest of the world. It serves as the lifeblood of the nation, contributing to the creation of advanced weaponry, futuristic infrastructure, and groundbreaking medical innovations", 50000)
    )
}